# infrastructure/prometheus/alertmanager/config.yml
global:
  resolve_timeout: 15m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@crypto-stats.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: '${SMTP_PASSWORD}'
  slack_api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

templates:
- '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack-notifications'
  routes:
  - match_re:
      severity: critical
    receiver: 'pagerduty-emergency'
    continue: false
  - match:
      team: database
    receiver: 'database-team'
  - match:
      team: api
    receiver: 'api-team'
  - match:
      component: infrastructure
    receiver: 'infra-team'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster']

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts-general'
    send_resolved: true
    title: '{{ template "slack.title" . }}'
    text: '{{ template "slack.text" . }}'
    icon_emoji: ':prometheus:'
    http_config:
      bearer_token: '${SLACK_TOKEN}'

- name: 'pagerduty-emergency'
  pagerduty_configs:
  - service_key: '${PAGERDUTY_KEY}'
    severity: 'critical'
    details:
      firing: '{{ template "pagerduty.description" . }}'

- name: 'database-team'
  email_configs:
  - to: 'database-team@crypto-stats.com'
    headers:
      Subject: '[DB Alert] {{ .CommonLabels.alertname }}'
  webhook_configs:
  - url: 'http://database-bot/webhooks'

- name: 'api-team'
  slack_configs:
  - channel: '#api-alerts'
    send_resolved: true
  opsgenie_configs:
  - api_key: '${OPSGENIE_API_KEY}'
    message: 'API Alert - {{ .CommonLabels.alertname }}'
    priority: 'P1'

- name: 'infra-team'
  victorops_configs:
  - api_key: '${VICTOROPS_API_KEY}'
    routing_key: 'infra'
  webhook_configs:
  - url: 'http://infra-bot:8080/alerts'

# infrastructure/prometheus/templates/slack.tmpl
{{ define "slack.title" }}[{{ .Status | title }}] {{ .CommonLabels.alertname }}{{ end }}
{{ define "slack.text" }}
*Alert*: {{ .CommonLabels.alertname }}
*Severity*: {{ .CommonLabels.severity }}
*Description*: {{ .CommonAnnotations.description }}
*Graph*: <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
*Dashboard*: <https://grafana.example.com/d/{{ .CommonLabels.dashboard }}|:grafana:>
*Runbook*: <{{ .CommonAnnotations.runbook }}|:book:>
{{ end }}